services:
  example-nodejs:
    build: .
    volumes:
      - .:/app
    ports:
      - 3500:3500
    networks:
      - default
      - coffee-payments-gateway_paynet
    tty: true
    stdin_open: true

networks:
  coffee-payments-gateway_paynet:
    external: true
